
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/navbar'; // Import the component
import Footer from './components/footer';

const inter = Inter({ subsets: ["latin"] });

 export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">

      <head>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>  
      </head>
         
      <body>

      <div style={{ backgroundImage: `url("/Background_-_Tela_Inicial.png")`, backgroundSize: "100% 100%", height: "100vh" }}>
      <Navbar></Navbar>
    
       {/* Layout UI */}

      <main>{children}</main>

      </div>
    
      <Footer />


      </body>

    </html>
  );
}
